using System.Text;
using System.Text.RegularExpressions;
using FactChecker.Core.Enums;
using FactChecker.Core.Interfaces;
using FactChecker.Core.Models;
using Microsoft.Extensions.Logging;
using YoutubeExplode;
using YoutubeExplode.Videos.ClosedCaptions;

namespace FactChecker.Infrastructure.YouTube;

#pragma warning disable CA1001 // YoutubeClient wraps an IHttpClientFactory-managed HttpClient; the factory owns the handler lifetime
public sealed partial class YouTubeTranscriptExtractor : ITranscriptExtractor
{
#pragma warning restore CA1001
    private static readonly Regex HtmlTagPattern = new(@"<[^>]+>", RegexOptions.Compiled);
    private static readonly Regex WhitespacePattern = new(@"\s+", RegexOptions.Compiled);

    private readonly YoutubeClient _youtubeClient;
    private readonly ILogger<YouTubeTranscriptExtractor> _logger;

    public YouTubeTranscriptExtractor(IHttpClientFactory httpClientFactory, ILogger<YouTubeTranscriptExtractor> logger)
    {
        ArgumentNullException.ThrowIfNull(httpClientFactory);
        ArgumentNullException.ThrowIfNull(logger);
        var httpClient = httpClientFactory.CreateClient(nameof(YouTubeTranscriptExtractor));
        _youtubeClient = new YoutubeClient(httpClient);
        _logger = logger;
    }

    public async Task<Transcript> ExtractAsync(string videoId, CancellationToken ct = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(videoId);

        ClosedCaptionManifest manifest;
        try
        {
            manifest = await _youtubeClient.Videos.ClosedCaptions
                .GetManifestAsync(videoId, ct)
                .ConfigureAwait(false);
        }
        catch (HttpRequestException ex)
        {
            LogHttpError(ex, videoId);
            throw new TranscriptNotAvailableException(videoId, ex);
        }
#pragma warning disable CA1031 // YoutubeExplode throws various undocumented exception types for unavailable videos
        catch (Exception ex) when (ex is not OperationCanceledException)
        {
            LogUnexpectedError(ex, videoId);
            throw new TranscriptNotAvailableException(videoId, ex);
        }
#pragma warning restore CA1031

        // Prefer manual captions; fall back to auto-generated
        var trackInfo =
            manifest.Tracks.FirstOrDefault(t => !t.IsAutoGenerated) ??
            manifest.Tracks.FirstOrDefault(t => t.IsAutoGenerated);

        if (trackInfo is null)
        {
            LogNoCaptionTracks(videoId);
            throw new TranscriptNotAvailableException(videoId);
        }

        var quality = trackInfo.IsAutoGenerated
            ? TranscriptQuality.AutoGenerated
            : TranscriptQuality.Manual;

        var track = await _youtubeClient.Videos.ClosedCaptions
            .GetAsync(trackInfo, ct)
            .ConfigureAwait(false);

        var text = BuildText(track.Captions);
        var wordCount = CountWords(text);

        LogTranscriptExtracted(videoId, wordCount, quality);

        return new Transcript(text, quality, wordCount);
    }

    private static string BuildText(IReadOnlyList<ClosedCaption> captions)
    {
        var sb = new StringBuilder(captions.Count * 40);

        foreach (var caption in captions)
        {
            var cleaned = HtmlTagPattern.Replace(caption.Text, " ");
            sb.Append(cleaned);
            sb.Append(' ');
        }

        return WhitespacePattern.Replace(sb.ToString().Trim(), " ");
    }

    private static int CountWords(string text) =>
        string.IsNullOrWhiteSpace(text)
            ? 0
            : WhitespacePattern.Split(text.Trim()).Length;

    [LoggerMessage(Level = LogLevel.Warning, Message = "HTTP error fetching caption manifest for video {VideoId}")]
    private partial void LogHttpError(Exception ex, string videoId);

    [LoggerMessage(Level = LogLevel.Warning, Message = "Unexpected error fetching caption manifest for video {VideoId}")]
    private partial void LogUnexpectedError(Exception ex, string videoId);

    [LoggerMessage(Level = LogLevel.Warning, Message = "No caption tracks available for video {VideoId}")]
    private partial void LogNoCaptionTracks(string videoId);

    [LoggerMessage(Level = LogLevel.Debug, Message = "Transcript extracted for video {VideoId}: {WordCount} words, quality={Quality}")]
    private partial void LogTranscriptExtracted(string videoId, int wordCount, TranscriptQuality quality);
}
