using System.Text;
using System.Text.RegularExpressions;
using FactChecker.Core.Enums;
using FactChecker.Core.Interfaces;
using FactChecker.Core.Models;
using YoutubeExplode;
using YoutubeExplode.Videos.ClosedCaptions;

namespace FactChecker.Infrastructure.YouTube;

public sealed class YouTubeTranscriptExtractor : ITranscriptExtractor
{
    private static readonly Regex HtmlTagPattern = new(@"<[^>]+>", RegexOptions.Compiled);
    private static readonly Regex WhitespacePattern = new(@"\s+", RegexOptions.Compiled);

    private readonly YoutubeClient _youtubeClient;

    public YouTubeTranscriptExtractor(IHttpClientFactory httpClientFactory)
    {
        ArgumentNullException.ThrowIfNull(httpClientFactory);
        var httpClient = httpClientFactory.CreateClient(nameof(YouTubeTranscriptExtractor));
        _youtubeClient = new YoutubeClient(httpClient);
    }

    public async Task<Transcript> ExtractAsync(string videoId, CancellationToken ct = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(videoId);

        ClosedCaptionManifest manifest;
        try
        {
            manifest = await _youtubeClient.Videos.ClosedCaptions
                .GetManifestAsync(videoId, ct)
                .ConfigureAwait(false);
        }
        catch (HttpRequestException ex)
        {
            throw new TranscriptNotAvailableException(videoId, ex);
        }
#pragma warning disable CA1031 // YoutubeExplode throws various undocumented exception types for unavailable videos
        catch (Exception ex) when (ex is not OperationCanceledException)
        {
            throw new TranscriptNotAvailableException(videoId, ex);
        }
#pragma warning restore CA1031

        // Prefer manual captions; fall back to auto-generated
        var trackInfo =
            manifest.Tracks.FirstOrDefault(t => !t.IsAutoGenerated) ??
            manifest.Tracks.FirstOrDefault(t => t.IsAutoGenerated);

        if (trackInfo is null)
            throw new TranscriptNotAvailableException(videoId);

        var quality = trackInfo.IsAutoGenerated
            ? TranscriptQuality.AutoGenerated
            : TranscriptQuality.Manual;

        var track = await _youtubeClient.Videos.ClosedCaptions
            .GetAsync(trackInfo, ct)
            .ConfigureAwait(false);

        var text = BuildText(track.Captions);
        var wordCount = CountWords(text);

        return new Transcript(text, quality, wordCount);
    }

    private static string BuildText(IReadOnlyList<ClosedCaption> captions)
    {
        var sb = new StringBuilder(captions.Count * 40);

        foreach (var caption in captions)
        {
            var cleaned = HtmlTagPattern.Replace(caption.Text, " ");
            sb.Append(cleaned);
            sb.Append(' ');
        }

        return WhitespacePattern.Replace(sb.ToString().Trim(), " ");
    }

    private static int CountWords(string text) =>
        string.IsNullOrWhiteSpace(text)
            ? 0
            : WhitespacePattern.Split(text.Trim()).Length;
}
