using FactChecker.Core.Enums;
using FactChecker.Core.Models;
using FactChecker.Core.Scoring;

namespace FactChecker.Core.Tests.Scoring;

public class DefaultScoringEngineTests
{
    private readonly DefaultScoringEngine _engine = new();

    // ── helpers ─────────────────────────────────────────────────────────────

    private static Claim Claim(string id, int importance) =>
        new(id, $"Claim {id}", $"Context {id}", importance);

    private static FactCheck Fact(string claimId, Verdict verdict, params Source[] sources) =>
        new(claimId, verdict, Confidence.High, "Reasoning", sources);

    private static Source AccessibleSource() =>
        new(new Uri("https://example.com"), "Title", "Snippet", IsAccessible: true);

    private static Source InaccessibleSource() =>
        new(new Uri("https://example.com/broken"), "Title", "Snippet", IsAccessible: false);

    // ── accuracy score ───────────────────────────────────────────────────────

    [Fact]
    public void AllSupported_AccuracyIsHundred()
    {
        var claims = new[] { Claim("c1", 3), Claim("c2", 3) };
        var facts = new[] { Fact("c1", Verdict.Supported), Fact("c2", Verdict.Supported) };

        var result = _engine.Calculate(claims, facts, ContentDomain.General, TranscriptQuality.Manual);

        Assert.Equal(100.0, result.AccuracyScore);
    }

    [Fact]
    public void AllRefuted_AccuracyIsZero()
    {
        var claims = new[] { Claim("c1", 3), Claim("c2", 3) };
        var facts = new[] { Fact("c1", Verdict.Refuted), Fact("c2", Verdict.Refuted) };

        var result = _engine.Calculate(claims, facts, ContentDomain.General, TranscriptQuality.Manual);

        Assert.Equal(0.0, result.AccuracyScore);
    }

    [Fact]
    public void MixedVerdicts_AccuracyIsImportanceWeighted()
    {
        // c1 importance=1 (weight=1/4), c2 importance=3 (weight=3/4)
        var claims = new[] { Claim("c1", 1), Claim("c2", 3) };
        var facts = new[]
        {
            Fact("c1", Verdict.Supported),      // 100 * 0.25 = 25
            Fact("c2", Verdict.Refuted),         // 0   * 0.75 = 0
        };

        var result = _engine.Calculate(claims, facts, ContentDomain.General, TranscriptQuality.AutoGenerated);

        Assert.Equal(25.0, result.AccuracyScore, precision: 5);
    }

    [Fact]
    public void PartiallySupported_GivesSixtyPercent()
    {
        var claims = new[] { Claim("c1", 2) };
        var facts = new[] { Fact("c1", Verdict.PartiallySupported) };

        var result = _engine.Calculate(claims, facts, ContentDomain.General, TranscriptQuality.AutoGenerated);

        Assert.Equal(60.0, result.AccuracyScore, precision: 5);
    }

    [Fact]
    public void Unverifiable_GivesFourtyPercent()
    {
        var claims = new[] { Claim("c1", 2) };
        var facts = new[] { Fact("c1", Verdict.Unverifiable) };

        var result = _engine.Calculate(claims, facts, ContentDomain.General, TranscriptQuality.AutoGenerated);

        Assert.Equal(40.0, result.AccuracyScore, precision: 5);
    }

    // ── worst-claim penalty (Rule R4) ────────────────────────────────────────

    [Fact]
    public void OneHighImportanceRefuted_PenalisedFifteen()
    {
        // One high-importance (>=4) refuted claim: penalty = 15
        var claims = new[] { Claim("c1", 4), Claim("c2", 3) };
        var facts = new[]
        {
            Fact("c1", Verdict.Refuted),
            Fact("c2", Verdict.Supported),
        };

        // Unpenalised accuracy: (0 * 4/7) + (100 * 3/7) ≈ 42.857
        // After penalty: max(0, 42.857 - 15) ≈ 27.857
        var result = _engine.Calculate(claims, facts, ContentDomain.General, TranscriptQuality.AutoGenerated);

        Assert.True(result.AccuracyScore < 42.857, "Penalty should have reduced accuracy.");
    }

    [Fact]
    public void TwoHighImportanceRefuted_PenalisedThirty()
    {
        var claims = new[] { Claim("c1", 5), Claim("c2", 5) };
        var facts = new[] { Fact("c1", Verdict.Refuted), Fact("c2", Verdict.Refuted) };

        // Unpenalised = 0, penalty = min(2*15, 30) = 30 → max(0, 0-30) = 0
        var result = _engine.Calculate(claims, facts, ContentDomain.General, TranscriptQuality.AutoGenerated);

        Assert.Equal(0.0, result.AccuracyScore);
    }

    [Fact]
    public void ThreeOrMoreHighImportanceRefuted_PenaltyCappedAtThirty()
    {
        var claims = new[] { Claim("c1", 5), Claim("c2", 5), Claim("c3", 5), Claim("c4", 2) };
        var facts = new[]
        {
            Fact("c1", Verdict.Refuted),
            Fact("c2", Verdict.Refuted),
            Fact("c3", Verdict.Refuted),
            Fact("c4", Verdict.Supported),
        };

        // 3 high-importance refuted → penalty = min(45, 30) = 30 (capped)
        var result = _engine.Calculate(claims, facts, ContentDomain.General, TranscriptQuality.AutoGenerated);

        Assert.Equal(0.0, result.AccuracyScore); // All supported score < 30, so clamped to 0
    }

    [Fact]
    public void LowImportanceRefuted_NoPenalty()
    {
        // Importance=3 is below threshold of 4
        var claims = new[] { Claim("c1", 3) };
        var facts = new[] { Fact("c1", Verdict.Refuted) };

        var result = _engine.Calculate(claims, facts, ContentDomain.General, TranscriptQuality.AutoGenerated);

        // No penalty — worst-claim penalty only applies to Importance >= 4
        Assert.Equal(0.0, result.AccuracyScore);
    }

    // ── Rule R3: NotAClaim exclusion ─────────────────────────────────────────

    [Fact]
    public void NotAClaim_ExcludedFromAccuracy()
    {
        var claims = new[] { Claim("c1", 3), Claim("c2", 3) };
        var facts = new[]
        {
            Fact("c1", Verdict.Supported),
            Fact("c2", Verdict.NotAClaim),
        };

        // Only c1 counts; accuracy should be 100
        var result = _engine.Calculate(claims, facts, ContentDomain.General, TranscriptQuality.AutoGenerated);

        Assert.Equal(100.0, result.AccuracyScore);
    }

    [Fact]
    public void AllNotAClaim_AccuracyIsZero()
    {
        var claims = new[] { Claim("c1", 3) };
        var facts = new[] { Fact("c1", Verdict.NotAClaim) };

        var result = _engine.Calculate(claims, facts, ContentDomain.General, TranscriptQuality.AutoGenerated);

        Assert.Equal(0.0, result.AccuracyScore);
        Assert.Equal(0.0, result.VerifiabilityScore);
    }

    // ── source quality score ─────────────────────────────────────────────────

    [Fact]
    public void AllSourcesAccessible_SourceQualityIsHundred()
    {
        var claims = new[] { Claim("c1", 3) };
        var facts = new[] { Fact("c1", Verdict.Supported, AccessibleSource(), AccessibleSource()) };

        var result = _engine.Calculate(claims, facts, ContentDomain.General, TranscriptQuality.AutoGenerated);

        Assert.Equal(100.0, result.SourceQualityScore);
    }

    [Fact]
    public void NoSourcesAccessible_SourceQualityIsZero()
    {
        var claims = new[] { Claim("c1", 3) };
        var facts = new[] { Fact("c1", Verdict.Supported, InaccessibleSource()) };

        var result = _engine.Calculate(claims, facts, ContentDomain.General, TranscriptQuality.AutoGenerated);

        Assert.Equal(0.0, result.SourceQualityScore);
    }

    [Fact]
    public void HalfSourcesAccessible_SourceQualityIsFifty()
    {
        var claims = new[] { Claim("c1", 3) };
        var facts = new[] { Fact("c1", Verdict.Supported, AccessibleSource(), InaccessibleSource()) };

        var result = _engine.Calculate(claims, facts, ContentDomain.General, TranscriptQuality.AutoGenerated);

        Assert.Equal(50.0, result.SourceQualityScore, precision: 5);
    }

    [Fact]
    public void NoSources_SourceQualityIsZero()
    {
        var claims = new[] { Claim("c1", 3) };
        var facts = new[] { Fact("c1", Verdict.Supported) };

        var result = _engine.Calculate(claims, facts, ContentDomain.General, TranscriptQuality.AutoGenerated);

        Assert.Equal(0.0, result.SourceQualityScore);
    }

    // ── verifiability score ──────────────────────────────────────────────────

    [Fact]
    public void AllVerifiable_VerifiabilityIsHundred()
    {
        var claims = new[] { Claim("c1", 3), Claim("c2", 3) };
        var facts = new[] { Fact("c1", Verdict.Supported), Fact("c2", Verdict.Refuted) };

        var result = _engine.Calculate(claims, facts, ContentDomain.General, TranscriptQuality.AutoGenerated);

        Assert.Equal(100.0, result.VerifiabilityScore);
    }

    [Fact]
    public void AllUnverifiable_VerifiabilityIsZero()
    {
        var claims = new[] { Claim("c1", 3) };
        var facts = new[] { Fact("c1", Verdict.Unverifiable) };

        var result = _engine.Calculate(claims, facts, ContentDomain.General, TranscriptQuality.AutoGenerated);

        Assert.Equal(0.0, result.VerifiabilityScore);
    }

    [Fact]
    public void HalfUnverifiable_VerifiabilityIsFifty()
    {
        var claims = new[] { Claim("c1", 3), Claim("c2", 3) };
        var facts = new[] { Fact("c1", Verdict.Supported), Fact("c2", Verdict.Unverifiable) };

        var result = _engine.Calculate(claims, facts, ContentDomain.General, TranscriptQuality.AutoGenerated);

        Assert.Equal(50.0, result.VerifiabilityScore, precision: 5);
    }

    // ── aggregate score ──────────────────────────────────────────────────────

    [Fact]
    public void ManualTranscript_AddsUpToFivePointBonus()
    {
        var claims = new[] { Claim("c1", 3) };
        var facts = new[] { Fact("c1", Verdict.Supported) };

        var manual = _engine.Calculate(claims, facts, ContentDomain.General, TranscriptQuality.Manual);
        var auto = _engine.Calculate(claims, facts, ContentDomain.General, TranscriptQuality.AutoGenerated);

        // Manual bonus = 0.05 * 100 = 5 points
        Assert.Equal(5.0, manual.AggregateScore - auto.AggregateScore, precision: 5);
    }

    [Fact]
    public void AllScoresHundred_AggregateIsHundred()
    {
        var claims = new[] { Claim("c1", 3) };
        var facts = new[] { Fact("c1", Verdict.Supported, AccessibleSource()) };

        var result = _engine.Calculate(claims, facts, ContentDomain.General, TranscriptQuality.Manual);

        Assert.Equal(100.0, result.AggregateScore, precision: 5);
    }

    [Fact]
    public void ScoresNeverExceedHundred()
    {
        var claims = new[] { Claim("c1", 5) };
        var facts = new[] { Fact("c1", Verdict.Supported, AccessibleSource()) };

        var result = _engine.Calculate(claims, facts, ContentDomain.General, TranscriptQuality.Manual);

        Assert.True(result.AccuracyScore <= 100);
        Assert.True(result.SourceQualityScore <= 100);
        Assert.True(result.VerifiabilityScore <= 100);
        Assert.True(result.AggregateScore <= 100);
    }

    [Fact]
    public void ScoresNeverGoBelowZero()
    {
        var claims = new[] { Claim("c1", 5), Claim("c2", 5) };
        var facts = new[] { Fact("c1", Verdict.Refuted), Fact("c2", Verdict.Refuted) };

        var result = _engine.Calculate(claims, facts, ContentDomain.General, TranscriptQuality.AutoGenerated);

        Assert.True(result.AccuracyScore >= 0);
        Assert.True(result.AggregateScore >= 0);
    }

    // ── edge cases ───────────────────────────────────────────────────────────

    [Fact]
    public void NoClaimsAtAll_AllScoresZero()
    {
        var result = _engine.Calculate([], [], ContentDomain.General, TranscriptQuality.AutoGenerated);

        Assert.Equal(0.0, result.AccuracyScore);
        Assert.Equal(0.0, result.SourceQualityScore);
        Assert.Equal(0.0, result.VerifiabilityScore);
    }

    [Fact]
    public void SingleClaim_ScoresCorrectly()
    {
        var claims = new[] { Claim("c1", 3) };
        var facts = new[] { Fact("c1", Verdict.Supported, AccessibleSource()) };

        var result = _engine.Calculate(claims, facts, ContentDomain.Health, TranscriptQuality.AutoGenerated);

        Assert.Equal(100.0, result.AccuracyScore);
        Assert.Equal(100.0, result.SourceQualityScore);
        Assert.Equal(100.0, result.VerifiabilityScore);
    }

    [Fact]
    public void ScoreMethod_IdentifiesAlgorithmVersion()
    {
        var result = _engine.Calculate([], [], ContentDomain.General, TranscriptQuality.AutoGenerated);

        Assert.Equal("v1.0-weighted", result.ScoreMethod);
    }

    [Fact]
    public void ClaimWithNoMatchingFactCheck_IsIgnored()
    {
        // Claim c2 has no fact-check — should not affect scoring
        var claims = new[] { Claim("c1", 3), Claim("c2", 3) };
        var facts = new[] { Fact("c1", Verdict.Supported) };

        var result = _engine.Calculate(claims, facts, ContentDomain.General, TranscriptQuality.AutoGenerated);

        Assert.Equal(100.0, result.AccuracyScore);
    }
}
